on:
  push:
    tags:
      - 'v*'
name: Publish
jobs:
  build:
    name: Release - ${{ matrix.platform.target }}
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/tags/test-release'
    strategy:
      matrix:
        platform:
          - release_for: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: badpiggies-cryptor-cli
            name: badpiggies-cryptor-cli-x86_64-unknown-linux-gnu.tar.gz
          - release_for: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: badpiggies-cryptor-cli
            name: badpiggies-cryptor-cli-aarch64-unknown-linux-gnu.tar.gz
          - release_for: apple-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: badpiggies-cryptor-cli
            name: badpiggies-cryptor-cli-x86_64-apple-darwin.tar.gz
          - release_for: apple-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            bin: badpiggies-cryptor-cli
            name: badpiggies-cryptor-cli-aarch64-apple-darwin.tar.gz
          - release_for: pc-windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: badpiggies-cryptor-cli.exe
            name: badpiggies-cryptor-cli-x86_64-pc-windows-msvc.tar.gz
          - release_for: pc-windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc
            bin: badpiggies-cryptor-cli.exe
            name: badpiggies-cryptor-cli-aarch64-pc-windows-msvc.tar.gz
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: "badpiggies-cryptor-cli*"
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: "badpiggies-cryptor-cli*"
        if: startsWith(github.ref, 'refs/tags/v')